In [5]:
!pip install pandas==1.0.0

In [6]:

import pandas as pd

In [7]:
import numpy as np

arr = np.random.randint(0, 10, size=(5, 3))
print(arr)

[[7 4 1]
 [2 0 8]
 [6 9 7]
 [7 1 5]
 [8 7 0]]


In [6]:
# Создание фрейма - просто вызвать конструктор
df = pd.DataFrame(data=arr)
# Фреймы удобнее отображать с помощью встроенных средств Jupyter
df

0  1  2
0  4  5  2
1  3  2  9
2  6  5  4
3  1  5  7
4  5  1  7

In [11]:
#Создайте фрейм с именами колонок 'col_1', 'col_2', 'col_3' и индексами по алфавиту ('A', 'B', 'C', ... или 'A', 'Б', 'В', ...).
arr = np.random.randint(0, 10, size=(5, 3))
print(arr)
df = pd.DataFrame(data=arr,columns=['col_1', 'col_2', 'col_3'],index=['A','B','C','D','E'])
df


[[1 5 7]
 [4 5 2]
 [3 2 1]
 [2 9 2]
 [8 5 9]]


col_1  col_2  col_3
A      1      5      7
B      4      5      2
C      3      2      1
D      2      9      2
E      8      5      9

In [12]:
#Создание фрейма из словарей
# Создается словарь, в котором ключи будут названиями колонок,
#   а значения - данные по этим колонкам
data = {
    'test_1_mark': [4.6, 3.8, 5.0, 4.5],
    'test_2_mark': [5.0, 3.9, 4.7, 4.5]
}

pd.DataFrame(data)

test_1_mark  test_2_mark
0          4.6          5.0
1          3.8          3.9
2          5.0          4.7
3          4.5          4.5

In [13]:
#создание массива словарей:
# Создается список записей, каждая запись представлена словарем
# В словаре ключи - названия колонок
# При создании фрейма pandas просмотри все возможные ключи словарей в списке
#   и создаст колонок по их названиям
data = [
    {
        'test_1_mark': 4.6,
        'test_2_mark': 5.0
    },
    {
        'test_1_mark': 3.8,
        'test_2_mark': 3.9
    },
    {
        'test_1_mark': 5.0
    },
]

pd.DataFrame(data)

test_1_mark  test_2_mark
0          4.6          5.0
1          3.8          3.9
2          5.0          NaN

In [14]:
#Типы данных
df = pd.DataFrame({'A': 1.,
                   'B': pd.Timestamp('20130102'),
                   'C': np.array([2.] * 4, dtype='float32'),
                   'D': np.array([3] * 4, dtype='int32'),
                   'E': pd.Categorical(["test", "train", "test", "train"]),
                   'F': 'foo'})
df

A          B    C  D      E    F
0  1.0 2013-01-02  2.0  3   test  foo
1  1.0 2013-01-02  2.0  3  train  foo
2  1.0 2013-01-02  2.0  3   test  foo
3  1.0 2013-01-02  2.0  3  train  foo

In [17]:
#Обзор данных
df = pd.DataFrame(
    data=np.random.randint(-10, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)

# Функция получения первых записей фрейма
# Аргументом задается количество выводимых данных
#   Если не задано - 5 по-умолчанию
df.head(4)

x1  x2  x3
0  -1   2   8
1  -9   3  -7
2   5   5   3
3  -1   5  -4

In [18]:
# Функция получения последних записей фрейма
# Аргументом задается количество выводимых данных
#   Если не задано - 5 по-умолчанию
df.tail(4)

x1  x2  x3
11  -4   9 -10
12 -10   4   2
13   6   2  -5
14  -1   6   1

In [19]:

# Функция отображения основной информации о фрейме:
#   Количество записей
#   Типы колонок
#   Количество ненулевых значений
#   Тип индекса
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      15 non-null     int32
 1   x2      15 non-null     int32
 2   x3      15 non-null     int32
dtypes: int32(3)
memory usage: 308.0 bytes


In [20]:
# Функция отображения статистики по численным колонкам
df.describe()

x1         x2         x3
count  15.000000  15.000000  15.000000
mean   -1.733333   2.266667  -1.533333
std     5.351457   5.624775   4.897035
min   -10.000000 -10.000000 -10.000000
25%    -6.000000  -0.500000  -4.500000
50%    -1.000000   4.000000  -3.000000
75%     3.000000   5.500000   2.000000
max     6.000000   9.000000   8.000000

In [24]:
# Атрибут получения индексов фрейма
df.index


RangeIndex(start=0, stop=15, step=1)

In [25]:
# Или чтобы представить в виде списка
list(df.index)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [26]:
# Атрибут получения имен колонок фрейма
df.columns

Index(['x1', 'x2', 'x3'], dtype='object')

In [27]:
 #Атрибут размерности фрейма
df.shape

(15, 3)

In [28]:
# Преобразование к двумерному массиву numpy
df.to_numpy()

array([[ -1,   2,   8],
       [ -9,   3,  -7],
       [  5,   5,   3],
       [ -1,   5,  -4],
       [ -2,  -5,   2],
       [  4, -10,   5],
       [ -6,  -3,  -2],
       [ -6,   9,  -4],
       [  5,   4,  -3],
       [  2,   8,  -3],
       [ -8,  -5,  -6],
       [ -4,   9, -10],
       [-10,   4,   2],
       [  6,   2,  -5],
       [ -1,   6,   1]])

In [29]:
# Получение транспонированного представления
# Колонки -> ряды, ряды -> колонки
df.T

0  1  2  3  4   5  6  7  8  9  10  11  12  13  14
x1 -1 -9  5 -1 -2   4 -6 -6  5  2  -8  -4 -10   6  -1
x2  2  3  5  5 -5 -10 -3  9  4  8  -5   9   4   2   6
x3  8 -7  3 -4  2   5 -2 -4 -3 -3  -6 -10   2  -5   1

In [34]:
# Обращение к данным

df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    columns=['x1', 'x2', 'x3']
)
df


x1  x2  x3
0   6   5   4
1   4   5   8
2   3   7   8
3   1   9   2
4   8   6   2

In [35]:
# Обращение к конкретной колонке
print(df['x1'])
print(type(df['x1']))

0    6
1    4
2    3
3    1
4    8
Name: x1, dtype: int32
<class 'pandas.core.series.Series'>


In [36]:
data = {
    'feature1': np.arange(15),
    'feature2': np.linspace(0, 10, 15),
    'feature3': 'string',
}
df = pd.DataFrame(data, index=list('ABCDEFGHIJKLMNO'))
df.head()

feature1  feature2 feature3
A         0  0.000000   string
B         1  0.714286   string
C         2  1.428571   string
D         3  2.142857   string
E         4  2.857143   string

In [37]:
df.iloc[2]

feature1          2
feature2    1.42857
feature3     string
Name: C, dtype: object

In [38]:
df.loc['C']

feature1          2
feature2    1.42857
feature3     string
Name: C, dtype: object

In [39]:

df.iloc[2, 1]

1.4285714285714286

In [40]:
df.loc['C', 'feature2']

1.4285714285714286

In [57]:
# Выведите часть фрейма со второго ряда по девятый (индексы с 'C' по 'I') и только feature1 и feature3:
data = {
    'feature1': np.arange(15),
    'feature2': np.linspace(0, 10, 15),
    'feature3': 'string',
}
df = pd.DataFrame(data, index=list('ABCDEFGHIJKLMNO'))
df.head()

feature1  feature2 feature3
A         0  0.000000   string
B         1  0.714286   string
C         2  1.428571   string
D         3  2.142857   string
E         4  2.857143   string

In [66]:
df1=df.iloc[:,[0,2]]
df2=df1.loc['C':'I']
df2

feature1 feature3
C         2   string
D         3   string
E         4   string
F         5   string
G         6   string
H         7   string
I         8   string

In [67]:
# Условная индексация
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   8   8   4
1   6   0   7
2   4   2   1

In [68]:
df['x1'] > 5

0      True
1      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11     True
12     True
13     True
14    False
Name: x1, dtype: bool

In [69]:
mask = df['x1'] > 5
df[mask]

x1  x2  x3
0    8   8   4
1    6   0   7
3    7   5   6
8    7   6   7
11   9   0   3
12   6   9   2
13   8   1   5

In [70]:
df[~(df['x1'] > 5)]

x1  x2  x3
2    4   2   1
4    1   6   3
5    5   7   7
6    2   7   4
7    3   7   2
9    2   0   6
10   2   0   8
14   4   4   0

In [71]:
# Выберите записи во фрейме, которые по признаку x1 имеют значение больше 3, а по признаку x3 - меньше 8.
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   5   2   4
1   0   9   3
2   1   7   1

In [76]:
mask = (df['x1'] > 3)&(df['x3']<8)
df1=df[mask]
df1

x1  x2  x3
0    5   2   4
4    4   1   0
6    9   8   0
7    7   9   4
8    4   9   7
9    5   7   0
12   8   1   0

In [77]:
df1.loc[:,['x1','x2']]

x1  x2
0    5   2
4    4   1
6    9   8
7    7   9
8    4   9
9    5   7
12   8   1

In [79]:
#С помощью метода DataFrame.query() получите записи, которые соответсвуют условию сравнения колонок
df = pd.DataFrame(
    [[1, 2, 6], [5, 1, 1], [8, 4, 6], [4, 1, 1], [9, 9, 0], [-1, 2, 1], [5, 5, 5]],
    columns = ['x1', 'x2', 'x3']
)
df.query('x1>x3')


x1  x2  x3
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0

In [80]:
mask = (df['x1'] > df['x3'])
df[mask]

x1  x2  x3
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0

In [81]:
# Операции с рядами
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   3   8   9
1   2   4   6
2   0   2   9

In [82]:
# Добавление новой колонки
# Создать новую колонку можно по аналогии с новым ключем в словаре
# Сложение нескольких Series и запись в новую колонку
df['x1+x2'] = df['x1'] + df['x2']
df.head(3)

x1  x2  x3  x1+x2
0   3   8   9     11
1   2   4   6      6
2   0   2   9      2

In [83]:
# Поэлементное умножение
df['x1*x3'] = df['x1'] * df['x3']
df.head(3)

x1  x2  x3  x1+x2  x1*x3
0   3   8   9     11     27
1   2   4   6      6     12
2   0   2   9      2      0

In [84]:
# Взятие среднего по колонке (метод Series.mean())
df['x1'].mean()

5.533333333333333

In [85]:
# Использование функций numpy для работы с колонками
df['x2_exp'] = np.exp(df['x2'])
df.head(3)

x1  x2  x3  x1+x2  x1*x3       x2_exp
0   3   8   9     11     27  2980.957987
1   2   4   6      6     12    54.598150
2   0   2   9      2      0     7.389056

In [86]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(3, 3)), 
    columns=['x1', 'x2', 'x3']
)
df

x1  x2  x3
0   4   2   3
1   2   8   8
2   9   2   4

In [87]:

# Обязательно требование к функции - один аргумент
# Эта функция будет передана в apply() и pandas
#   будет вызывать ее и передавать в нее 
#   по одному элементу из ряда
# Возвращать функция должна результат операции над элементом
def my_func(x):
    print(type(x))
    print(x)
    return x*2

df['result'] = df['x1'].apply(my_func)
df

<class 'int'>
4
<class 'int'>
2
<class 'int'>
9


x1  x2  x3  result
0   4   2   3       8
1   2   8   8       4
2   9   2   4      18

In [88]:
# Переименование колонок / индексов
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)


x1  x2  x3
0   8   4   4
1   8   8   3
2   1   3   5

In [89]:
# Методу передается в аргумент columns словарь, 
#   в котором ключи - имена колонок,
#   значения - новые имена для переименования
df.rename(
    columns={
        'x1': 'new_name_for_x1',
        'x3': 'that_not_x3' 
    },
    inplace=True
)
df.head(3)

new_name_for_x1  x2  that_not_x3
0                8   4            4
1                8   8            3
2                1   3            5

In [90]:
# Переименуйте индексы и колонки во фрейме
# TODO - переименуйте индексы [A, C] -> [indA, indC] 
#           и колонки [x1, x3] -> [new1, new3]
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    index=['A', 'B', 'C', 'D', 'E'], 
    columns=['x1', 'x2', 'x3']
)
df

x1  x2  x3
A   4   0   1
B   1   8   2
C   8   4   3
D   8   8   6
E   2   6   8

In [93]:
df.rename(
    columns={
        'x1': 'new1',
        'x3': 'new3' 
    },
    index={'A': 'indA',
           'C': 'indC'    
    },
    inplace=True
)
df

new1  x2  new3
indA     4   0     1
B        1   8     2
indC     8   4     3
D        8   8     6
E        2   6     8

In [94]:
# Удаление колонок / строк
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   2   8   9
1   9   8   2
2   8   1   1

In [95]:
df.drop(columns=['x2'], inplace=True)
df.head(3)

x1  x3
0   2   9
1   9   2
2   8   1

In [96]:
# Определение количества NaN
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.iloc[0, :2] = np.nan
df.iloc[2, 1:] = np.nan

df

x1   x2   x3
0  NaN  NaN  2.0
1  2.0  0.0  3.0
2  0.0  NaN  NaN
3  1.0  6.0  5.0
4  0.0  4.0  3.0

In [97]:
df.isna()

x1     x2     x3
0   True   True  False
1  False  False  False
2  False   True   True
3  False  False  False
4  False  False  False

In [98]:
df.isna().sum()

x1    1
x2    2
x3    1
dtype: int64

In [99]:
# Заполнение пустых значений
df

x1   x2   x3
0  NaN  NaN  2.0
1  2.0  0.0  3.0
2  0.0  NaN  NaN
3  1.0  6.0  5.0
4  0.0  4.0  3.0

In [100]:
# Заполнение пустых ячеек во втором столбце цифрой 3
df['x2'].fillna(3, inplace=True)
df

x1   x2   x3
0  NaN  3.0  2.0
1  2.0  0.0  3.0
2  0.0  3.0  NaN
3  1.0  6.0  5.0
4  0.0  4.0  3.0

In [101]:
# Информация об уникальных значениях

df = pd.DataFrame({
    'col1': ['high', 'high', 'low', 'med', 'low', 'low', 'med', 'low', 'low', 'high'],
    'col2': [0, 1, 1, 2, 3, 1, 1, 2, 2, 2]
})
df

col1  col2
0  high     0
1  high     1
2   low     1
3   med     2
4   low     3
5   low     1
6   med     1
7   low     2
8   low     2
9  high     2

In [102]:
# Метод DataFrame.nunique() позволяет вывести 
#   количество уникальных значений в каждой колонке
# Результат - Series с индексами - названиями колонок
df.nunique()

col1    3
col2    4
dtype: int64

In [103]:
# Метод Series.value_counts() показывает уникальные значения в ряду
#   и указывает их количество
df['col1'].value_counts()

low     5
high    3
med     2
Name: col1, dtype: int64

In [104]:
# Результат - Series с индексами - уникальными значениями
df['col2'].value_counts()

2    4
1    4
3    1
0    1
Name: col2, dtype: int64

In [105]:
#Фильтрация
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6])),
                  index=['mouse', 'rabbit'],
                  columns=['col_one', 'col_two', 'col_three'])
df

col_one  col_two  col_three
mouse         1        2          3
rabbit        4        5          6

In [106]:
# Отфильтровать по именам колонок
# Аналогично df[['col_one', 'col_three']]
df.filter(items=['col_one', 'col_three'], axis='columns')

col_one  col_three
mouse         1          3
rabbit        4          6

In [107]:
# Отфильтровать по регулярному выражению
# Оставить только те колонки, которые оканчиваются на букву "o"
df.filter(regex='o$', axis='columns')

col_two
mouse         2
rabbit        5

In [108]:
# Отфильруйте записи по строке, содержащейся в имени индекса (аргумент like):

df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9])),
                  index=['dog in house', 'cat in house', 'pig in farm'],
                  columns=['x1', 'x2', 'x3'])
df

x1  x2  x3
dog in house   1   2   3
cat in house   4   5   6
pig in farm    7   8   9

In [109]:
# TODO - отфильтруйте по записям, должны остаться записи, 
#           индекс которых содержит слово "house"
df.filter(like='house', axis='index')

x1  x2  x3
dog in house   1   2   3
cat in house   4   5   6

In [110]:
# Сортировка
df = pd.DataFrame({
    'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    'col2': [2, 1, 9, 8, 7, 4],
    'col3': [0, 1, 9, 4, 2, 3],
    'col4': ['a', 'B', 'c', 'D', 'e', 'F']
}, index=['A', 'B', 'C', 'D', 'E', 'F'])
df

col1  col2  col3 col4
A    A     2     0    a
B    A     1     1    B
C    B     9     9    c
D  NaN     8     4    D
E    D     7     2    e
F    C     4     3    F

In [111]:
# Отсортируем записи колонки col2
# Именно поэтому в axis ставится rows, так как
#   операция производится в колонке по каждому ряду
df.sort_values(by='col2', axis='rows')

col1  col2  col3 col4
B    A     1     1    B
A    A     2     0    a
F    C     4     3    F
E    D     7     2    e
D  NaN     8     4    D
C    B     9     9    c

In [138]:
# TODO - отсортируйте данные индекса 3 по убыванию
df = pd.DataFrame(
    np.random.randint(0, 20, size=(5, 5)), 
    columns=['col1', 'col2', 'col3', 'col4', 'col5']
)
df

col1  col2  col3  col4  col5
0     0     4     1     2    12
1     1    19     1     8    17
2     2    17     0     8     3
3     3    12     5    16     0
4     7    19     6     6     4

In [140]:
df.sort_values(by=3, axis='columns',ascending=False)

col4  col2  col3  col1  col5
0     2     4     1     0    12
1     8    19     1     1    17
2     8    17     0     2     3
3    16    12     5     3     0
4     6    19     6     7     4

In [141]:
# Разделение данных на категории
df = pd.DataFrame({
    'temp': [59, 22, -10, 38, 20, 40, 38, 47, 20, 15, 13, 44, 57, 32, 38]
})
df.head()

temp
0    59
1    22
2   -10
3    38
4    20

In [142]:
# Можно задать свои границы диапазона и названия категорий
# Если планируется три категории, то границ должно быть на одну больше - 
#   так задаются диапазоны для категорий
df['temp_cat'] = pd.cut(
    x=df['temp'],
    bins=[-10, 10, 25, 60],
    labels=['low', 'medium', 'high'],
    # Флаг, чтобы самое левое значение границы входило в первый диапазон
    include_lowest=True
)
df.head()

temp temp_cat
0    59     high
1    22   medium
2   -10      low
3    38     high
4    20   medium

In [143]:
# Результат разделения имеет категориальный тип
df['temp_cat'].dtype

CategoricalDtype(categories=['low', 'medium', 'high'], ordered=True)

In [144]:
# Можно не задавать имена категориям, тогда он сам их назовет
result_after_cut = pd.cut(
    x=df['temp'],
    bins=[-10, 10, 25, 60],
    include_lowest=True
)
# Взглянем на имена
result_after_cut.unique()

[(25.0, 60.0], (10.0, 25.0], (-10.001, 10.0]]
Categories (3, interval[float64]): [(-10.001, 10.0] < (10.0, 25.0] < (25.0, 60.0]]

In [145]:
# Можно не задавать границы, лишь количество категорий - 
#   разделение будет на категории с одинаковой шириной диапазонов
result_after_cut = pd.cut(
    x=df['temp'],
    bins=3
)
result_after_cut.unique()

[(36.0, 59.0], (13.0, 36.0], (-10.069, 13.0]]
Categories (3, interval[float64]): [(-10.069, 13.0] < (13.0, 36.0] < (36.0, 59.0]]

In [153]:
#Разделите показатель качества в диапазоне [0, 100] на три группы: плохое [0-20], среднее (20-45], хорошее (45-85], отличное (85-100]. Выясните, что происходит со значениями, которые не попадают в диапазоны категорий:

df = pd.DataFrame({
    'quality': [ 7, 67, 21, 38,  2, -2, 79, 22,  5, 31, 77, 72, 23, 64, 99,45]
})
df

quality
0         7
1        67
2        21
3        38
4         2
5        -2
6        79
7        22
8         5
9        31
10       77
11       72
12       23
13       64
14       99
15       45

In [154]:
df['results'] = pd.cut(
    x=df['quality'],
    bins=[0, 20, 45, 85,100],
    labels=['bad', 'so-so', 'good','perfect'],
    # Флаг, чтобы самое левое значение границы входило в первый диапазон
    include_lowest=True
)
df

quality  results
0         7      bad
1        67     good
2        21    so-so
3        38    so-so
4         2      bad
5        -2      NaN
6        79     good
7        22    so-so
8         5      bad
9        31    so-so
10       77     good
11       72     good
12       23    so-so
13       64     good
14       99  perfect
15       45    so-so

In [155]:
# Агрегация данных
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [np.nan, np.nan, np.nan]],
                  columns=['A', 'B', 'C'])
df

A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [156]:
# Получим значения минимумов и средних по всем колонкам
# Принцип аналогичен операциям в numpy - 
#   для агрегации по колонка операция должна пройти по рядам,
#   соответсвенно, axis='rows'
df.aggregate(['min', 'mean'], axis='rows')

A    B    C
min   1.0  2.0  3.0
mean  4.0  5.0  6.0

In [157]:
# Зададим правила агрегации для каждой колонки
# Операции можно задавать строками или функциями numpy
df.aggregate({
    'A': ['sum', 'min'],
    'B': ['max', 'min'],
    'C': [np.sum, np.mean],
})

A    B     C
max    NaN  8.0   NaN
mean   NaN  NaN   6.0
min    1.0  2.0   NaN
sum   12.0  NaN  18.0

In [158]:
# Произведите агрегацию средним по рядам
df = pd.DataFrame(
    ([1, 2, 3], [4, 5, 6], [7, 8, 9]), 
    columns=['x1', 'x2', 'x3'])
df

x1  x2  x3
0   1   2   3
1   4   5   6
2   7   8   9

In [159]:
df.aggregate(['mean'], axis='columns')

mean
0   2.0
1   5.0
2   8.0

In [160]:
#Группировки
data = [
    [1, 4.7, 60],
    [3, 4.5, 45],
    [4, 4.8, 40],
    [1, 4.9, 58],
    [2, 4.1, 50],
    [2, 4.2, 49],
    [2, 4.4, 49],
    [3, 4.9, 46],
    [4, 4.3, 33],
]

stud_df = pd.DataFrame(data, columns=['Grade', 'Test_Mark', 'Time'])
stud_df

Grade  Test_Mark  Time
0      1        4.7    60
1      3        4.5    45
2      4        4.8    40
3      1        4.9    58
4      2        4.1    50
5      2        4.2    49
6      2        4.4    49
7      3        4.9    46
8      4        4.3    33

In [161]:
gr_stud_df = stud_df.groupby(by='Grade')

# Тип результата - pd.DataFrameGroupBy
print(type(gr_stud_df))

# Таким образом увидим словарь:
#   Ключи - названия групп
#   Значения - индексы из данных для группы
gr_stud_df.groups

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


{1: Int64Index([0, 3], dtype='int64'),
 2: Int64Index([4, 5, 6], dtype='int64'),
 3: Int64Index([1, 7], dtype='int64'),
 4: Int64Index([2, 8], dtype='int64')}

In [162]:
gr_stud_df.agg('mean')

Test_Mark       Time
Grade                      
1       4.800000  59.000000
2       4.233333  49.333333
3       4.700000  45.500000
4       4.550000  36.500000

In [163]:
# Более сложный вариант - найдем средние и минимальные время и оценку 

gr_stud_df.agg(['mean', 'min'])

Test_Mark            Time    
           mean  min       mean min
Grade                              
1      4.800000  4.7  59.000000  58
2      4.233333  4.1  49.333333  49
3      4.700000  4.5  45.500000  45
4      4.550000  4.3  36.500000  33

In [164]:
# Или зададим правила для каждого признака по отдельности

res = gr_stud_df.agg({
    'Test_Mark': ['mean', 'min'],
    'Time': ['min']
})

print(type(res))
res

<class 'pandas.core.frame.DataFrame'>


Test_Mark      Time
           mean  min  min
Grade                    
1      4.800000  4.7   58
2      4.233333  4.1   49
3      4.700000  4.5   45
4      4.550000  4.3   33

In [165]:
# Для обращения к данным просто используем несколько индексов, 
#   так как это DataFrame
res['Test_Mark']['mean']

Grade
1    4.800000
2    4.233333
3    4.700000
4    4.550000
Name: mean, dtype: float64

In [166]:
#Сгруппируйте данные по признаку x2 и найдите медиану и максимальное значения по признакам x1, x3:
df = pd.DataFrame({
    'x1': np.random.randint(10, 100, size=(200, )),
    'x2': np.random.choice(['low', 'high', 'medium'], size=(200, )),
    'x3': np.random.randint(-20, 30, size=(200, )),
})
df.head()

x1    x2  x3
0  45   low  16
1  17  high  -1
2  24  high  29
3  83  high  16
4  58  high  18

In [168]:
# TODO - произведите групировку данных
#           и получите средние и максимальные значения по каждой группе
gr_df = df.groupby(by='x2')
gr_df.groups

{'high': Int64Index([  1,   2,   3,   4,   5,  19,  25,  32,  33,  45,  47,  48,  50,
              51,  54,  55,  58,  59,  61,  65,  66,  68,  69,  70,  78,  84,
              88,  89,  92,  93,  95, 100, 101, 102, 105, 107, 111, 114, 116,
             117, 119, 123, 126, 127, 128, 129, 130, 131, 132, 135, 137, 138,
             140, 145, 146, 147, 152, 153, 154, 157, 167, 169, 172, 173, 176,
             182, 184, 188, 191, 197, 198],
            dtype='int64'),
 'low': Int64Index([  0,   7,   8,   9,  11,  20,  23,  24,  26,  28,  29,  34,  36,
              37,  38,  39,  40,  42,  44,  52,  57,  60,  62,  63,  64,  67,
              71,  73,  74,  75,  76,  79,  81,  82,  85,  86,  87,  91,  97,
              98, 104, 106, 108, 112, 113, 115, 124, 125, 133, 139, 142, 158,
             161, 162, 164, 166, 168, 170, 171, 175, 177, 178, 179, 181, 185,
             186, 189, 194, 196, 199],
            dtype='int64'),
 'medium': Int64Index([  6,  10,  12,  13,  14,  15,  16,  17,  18

In [170]:
gr_df.agg(['mean', 'max'])

x1            x3    
             mean max      mean max
x2                                 
high    55.901408  99  8.492958  29
low     54.914286  98  3.842857  28
medium  59.186441  97  3.389831  29

In [171]:
#Сохранение / загрузка данных (работа с CSV)
import string

df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3'],
    index=list(string.ascii_uppercase)[:15]
)
df.head(3)

x1  x2  x3
A   4   5   9
B   2   8   2
C   8   5   1

In [172]:
# Для сохранения задается путь до файла
df.to_csv('my_first_file.csv')

In [173]:
df = pd.read_csv('my_first_file.csv')
df.head(3)

Unnamed: 0  x1  x2  x3
0          A   4   5   9
1          B   2   8   2
2          C   8   5   1

In [174]:
df = pd.read_csv('my_first_file.csv', index_col=0)
df.head(3)

x1  x2  x3
A   4   5   9
B   2   8   2
C   8   5   1

In [175]:
# TODO - сохранить в файл no_index.csv без индексов

df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3'],
    index=list(string.ascii_uppercase)[:15]
)
df.head(3)


x1  x2  x3
A   3   5   5
B   6   3   2
C   1   6   7

In [176]:
df.to_csv('my_first_file.csv',index=False)

In [15]:
# TODO - создайте фрейм и настройте правильные типы колонок
#           DataFrame.info() дожен отображать указанные типы
df = pd.DataFrame({ 'Name': ['Svetlana', 'Ivan','Olga'],
                   'experience': np.linspace(0, 10, 3, dtype= 'float32'),
                   'age': np.linspace(18, 65, 3, dtype='int32'),
                   'color': pd.Categorical(["blue", "red", "black"]) })
df
            

Name  experience  age  color
0  Svetlana         0.0   18   blue
1      Ivan         5.0   41    red
2      Olga        10.0   65  black

In [16]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   Name        3 non-null      object  
 1   experience  3 non-null      float32 
 2   age         3 non-null      int32   
 3   color       3 non-null      category
dtypes: category(1), float32(1), int32(1), object(1)
memory usage: 283.0+ bytes


In [44]:
#Выберите числа в ряду ds1, которых нет в ряду ds2
ds1 = pd.Series([1, 2, 3, 4, 5])
ds2 = pd.Series([4, 5, 6, 7, 8, 1, 9])

# TODO - выберите значения в ds1, которых нет в ds2: 
# [2, 3]
mask=ds1.isin(ds2)
print(ds1[~mask])

1    2
2    3
dtype: int64


In [114]:
ds = pd.Series([2, 2, 2, 4, 4, 4, 3, 1, 1, 1, 1, 4])

# TODO - определите два наиболее частых значения в ряду (1, 4),
#           остальные замените значением 'Другое'
# ['Другое', 'Другое', 'Другое', 4, 4, 4, 'Другое', 1, 1, 1, 1, 4]
mask=ds.value_counts()
new_mask=max(mask)==mask
mask1=ds.replace(mask[~new_mask].index,'Другое')
print(mask1)

0     Другое
1     Другое
2     Другое
3          4
4          4
5          4
6     Другое
7          1
8          1
9          1
10         1
11         4
dtype: object


In [134]:
ds = pd.Series(['how', 'to', 'use', 'pandas?'])
print(ds)
# TODO - сделайте каждую первую букву заглавной с помощью Series.apply()
def change(x):
    return x.title()
ds.apply(change)


0        how
1         to
2        use
3    pandas?
dtype: object


0        How
1         To
2        Use
3    Pandas?
dtype: object

In [143]:
df = pd.DataFrame(
    np.random.randint(0, 4, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df
# TODO - выберите те записи, которые имеют x1 равный 
#           максимальному значению в колонке x1
mask = (df['x1']==df['x1'].max())
df1=df[mask]
df1

x1  x2  x3
1    3   0   0
4    3   3   0
8    3   1   2
9    3   3   1
10   3   1   0
14   3   1   1

In [145]:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')
df
# TODO - отобразите количество пропусков в данных по каждой колонке


Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [146]:
df.isna().sum()

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [147]:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')
df
# TODO - заполните NaN в колонке Min.Price средним значением по этой колонке
# NOTE - после заполнения убедитесь, что в этой колонке нет пропущенных


Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [148]:
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9       18.8      25.0   
1           NaN   Legend  Midsize  29.200000   33.9       38.7      18.0   
2          Audi       90  Compact  25.900000   29.1       32.3      20.0   
3          Audi      100  Midsize  17.118605   37.7       44.6      19.0   
4           BMW     535i  Midsize  17.118605   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3       23.7      18.0   
91        Volvo      240  Compact  21.800000   22.7       23.5      21.0   
92          NaN      850  Midsize  24.800000   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [149]:
df = pd.DataFrame(np.random.randint(0, 10, size=(5, 6)), columns=list('fbecda'))
df
# TODO - получите фрейм с отсортированными по именам колонкам (f e d c b a)
# NOTE - сортировка должна быть автоматической

f  b  e  c  d  a
0  7  2  4  3  5  8
1  1  6  2  2  2  2
2  2  9  2  3  8  1
3  8  7  5  9  8  2
4  7  0  8  4  7  1

In [175]:
df = df.reindex(sorted(df.columns, reverse=True), axis=1)
df

f  e  d  c  b  a
0  7  4  5  3  2  8
1  1  2  2  2  6  2
2  2  2  8  3  9  1
3  8  5  8  9  7  2
4  7  8  7  4  0  1

In [181]:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')
df
# TODO - отобразите запись с периодичностью во фрейме и определенные колонки
#Отобразите каждую 20ю запись во фрейме и только колонки Manufacturer, Model, Type:

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [196]:
df1=df.loc[:,['Manufacturer','Model','Type']]
new_df=df1.iloc[[20,40,60,80],:]
new_df

Manufacturer    Model     Type
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [198]:
#Получите ряд, который содержит длины строк:

ds = pd.Series(['how', 'to', 'use', 'pandas?'])
ds.str.len()
# TODO - создайте ряд, содержащий длины строк:
# 0    3
# 1    2
# 2    3
# 3    7
# dtype: int64

0    3
1    2
2    3
3    7
dtype: int64