In [2]:

import numpy as np

In [56]:
#Создание массива
arr_1d = np.array([1, 2, 3])
print(arr_1d)
print(type(arr_1d)) #тип массива
print(arr_1d.shape) #размерность массива
print(arr_1d[0])
print(arr_1d[2])
print(arr_1d[-1])

[1 2 3]


In [263]:
#СПОСОБЫ СОЗДАНИЯ МАССИВОВ
# Создание 2d массива
arr_2d=np.array([[1,2,3], [4,5,6]])
print(arr_2d)
# Создание массива фиксированного размера с произвольным наполнением
print('')
print(np.ndarray((5, 3)))
# Создание матрицы из нулей заданного размера
print('')
print(np.zeros((2, 3)))
# Создание матрицы из единиц заданного размера
print('')
print(np.ones((3, 2)))
# Создание массива, заполненного константным значением
print('')
print(np.full((3, 4), 5))
# 2D массив с единичной главной диагональю
print('')
print(np.eye(3, 2))
# Создание массива нулей с такой же размерностью, как уже существующий
print('')
arr_2d_new = np.array([[1, 2, 3], [4, 5, 6]])
print(np.zeros_like(arr_2d_new))
# Создание массива единиц с такой же размерностью, как уже существующий
print('')
arr1_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(np.ones_like(arr1_2d))
# Создание массива со случайными значениями в интервале [0; 1.0)
print('')
print(np.random.random((2,2)))
# Аналог функции range
print('')
print(np.arange(start=1, stop=10, step=1.5))
# Также создание диапазона значений, но уже с заданием количества элементов
print('')
print(np.linspace(start=1, stop=2, num=10))

[[1 2 3]
 [4 5 6]]

[[4.66839074e-313 2.97079411e-313 8.48798316e-313]
 [5.30498948e-313 6.36598738e-314 1.27319747e-313]
 [3.39519327e-313 4.66839074e-313 1.90979621e-313]
 [1.90979621e-313 4.45619116e-313 3.18299369e-313]
 [5.09278990e-313 5.94158822e-313 1.69759663e-313]]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

[[1. 0.]
 [0. 1.]
 [0. 0.]]

[[0 0 0]
 [0 0 0]]

[[1 1 1]
 [1 1 1]]

[[0.88583604 0.23942605]
 [0.34779652 0.97069311]]

[1.  2.5 4.  5.5 7.  8.5]

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [265]:
# Индексация массивов
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(arr[0])
print(arr[-2])
print(arr[5])
print(arr[2:8])
print(arr[:6])

1
9
6
[3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6]


In [266]:
# Перевернутый список

data = list(range(10))
print(data)
new=data[9::-1]
print(new)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [267]:
#Получение массива без первого и двух последних элементов

data = list(range(10))
print(data)
print(data[1:8:1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7]


In [272]:
# Индексация в матрицах

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)
print('')
print(arr[2])
print('')
print(arr[2, :])
print('')
print(arr[:, 1])
print('')
print(arr[1, :2])
print('')
new_arr = arr.copy()
print('')
print(arr)
new_arr[2, :] = arr[1, :]
print('')
print(new_arr)
print('')
print(arr[:2, :2])
print('')
print(arr[:2, :2].shape)
print('')
print(arr[:, [0, -1]])
print('')
print(arr[:, [0, 1]])
print('')
print(arr[[2, 0, 1], :])
print('')
print(arr[[2, 0], [1, 3]])
print('')
print(arr[2, 1], arr[0, 3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 9 10 11 12]

[ 9 10 11 12]

[ 2  6 10]

[5 6]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]

[[1 2]
 [5 6]]

(2, 2)

[[ 1  4]
 [ 5  8]
 [ 9 12]]

[[ 1  2]
 [ 5  6]
 [ 9 10]]

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]

[10  4]

10 4


In [273]:
# Переворачивание массива
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
row_indices = list(range(arr.shape[0]))
print(row_indices)
row_indices = list(reversed(row_indices))
print(row_indices)
print('----------------')
print(arr[row_indices])

[0, 1, 2]
[2, 1, 0]
----------------
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [278]:
#Получение массива без крайних рядов и колонок

data = np.random.randint(low=0, high=10, size=(5, 6))
print(data)
new_data=(data[[1,2,3],:])
new_data=(new_data[:,[1,2,3,4]])
print('----------------')
print(new_data)

[[2 2 3 6 4 8]
 [2 3 0 1 0 3]
 [2 5 6 8 8 0]
 [7 5 3 1 2 8]
 [8 2 3 6 8 3]]
----------------
[[3 0 1 0]
 [5 6 8 8]
 [5 3 1 2]]


In [277]:
#Перемешивание колонок

data = np.random.randint(low=0, high=10, size=(3, 6))
print(data)
data1=np.transpose(data)
new=np.random.permutation(data1)
new1=np.transpose(new)
print('----------------')
print(new1)

[[0 4 9 2 0 4]
 [2 4 9 1 6 3]
 [3 3 3 9 5 0]]
----------------
[[4 0 9 2 0 4]
 [4 2 9 1 6 3]
 [3 3 3 9 5 0]]


In [279]:
# Тип массива
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr.dtype)

int32


In [280]:
# Тип массива
arr = np.array([[1.5, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr.dtype)

float64


In [281]:
arr = np.array([[1.1, 1.6, 2.4], [-1.7, 2.6, -1.2]], dtype=int)
print(arr)
print(arr.dtype)

[[ 1  1  2]
 [-1  2 -1]]
int32


In [282]:
arr = np.array([[1.1, 1.6, 2.4], [-1.7, 2.6, -1.2]])
print(arr)
print(arr.dtype)
print('----------')
arr = arr.astype(int)
print(arr)
print(arr.dtype)

[[ 1.1  1.6  2.4]
 [-1.7  2.6 -1.2]]
float64
----------
[[ 1  1  2]
 [-1  2 -1]]
int32


In [283]:
arr = np.array([[1.1, 1.6, 2.4], [-1.7, 2.6, -1.2]], dtype=int)
print(arr)
print('----------')
arr[0, 1] = 10.12
print(arr)

[[ 1  1  2]
 [-1  2 -1]]
----------
[[ 1 10  2]
 [-1  2 -1]]


In [284]:
# Булевы операции
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)
result = arr > 6
print('----------')
print(result)
print('  ')
print(result.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
  
bool


In [285]:
result_1 = arr > 6
result_2 = arr < 10
print(result_1)
print('  ')
print(result_2)
print('----------')
print(result_1 & result_2)
print('  ')
print((arr > 6) & (arr < 10))

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
  
[[ True  True  True  True]
 [ True  True  True  True]
 [ True False False False]]
----------
[[False False False False]
 [False False  True  True]
 [ True False False False]]
  
[[False False False False]
 [False False  True  True]
 [ True False False False]]


In [286]:
# Определить, имеется ли хоть одно значение больше пяти и меньше восьми
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)
print('----------')
arr_sravn=[(arr > 5) & (arr < 8)]
print(arr_sravn)
print('   ')
print(np.any(arr_sravn))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------
[array([[False, False, False, False],
       [False,  True,  True, False],
       [False, False, False, False]])]
   
True


In [287]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
mask = arr > 6
print(mask)
print('   ')
print(arr[mask])

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
   
[ 7  8  9 10 11 12]


In [288]:
# Объединение массива в строку
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.flatten())

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [292]:
# Операции с матрицами
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
# Сложение
print(x + y)
print(np.add(x, y))
print('-----')
# Вычитание
print(x - y)
print(np.subtract(x, y))
print('-----')
# Умножение
print(x * y)
print(np.multiply(x, y))
print('-----')
# Деление
print(x / y)
print(np.divide(x, y))
print('-----')
# поэлементное извлечение корня
print(np.sqrt(x))
print('-----')
# Матричное умножение
print(x @ y)
print(x.dot(y))
print(np.dot(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
-----
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
-----
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
-----
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
-----
[[1.         1.41421356]
 [1.73205081 2.        ]]
-----
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [290]:
# Умножение матрицы на число
x = np.array([[1,2],[3,4]], dtype=np.float64)
k = 1.5
print(k*x)

[[1.5 3. ]
 [4.5 6. ]]


In [293]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
v = np.array([1, 2])
print(x @ v)
print('  ')
print(x.dot(v))
print('  ')
print(np.dot(x, v))

[ 5. 11.]
  
[ 5. 11.]
  
[ 5. 11.]


In [294]:
w = np.array([3, 4])

print(w @ v)
print('  ')
print(w.dot(v))
print('  ')
print(np.dot(w, v))

11
  
11
  
11


In [295]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.shape)
print('--------')
print(np.transpose(x))
print(x.T)
print(x.T.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
--------
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [297]:
x = np.array([[1, 2, 3], [5, 4, 3]])
print(x)
# Возьмем среднее значение всего массива
print(np.mean(x))
print(np.mean(x, axis=None))
# Получим сумму значений всего массива
print(np.sum(x))
print(np.sum(x, axis=None))
# Получим среднее по каждому столбцу
print(np.mean(x, axis=0))
# Получим среднее по каждой строке
print(np.mean(x, axis=1))

[[1 2 3]
 [5 4 3]]
3.0
3.0
18
18
[3. 3. 3.]
[2. 4.]


In [298]:
#Операция получения суммы элементов по всем столбцам
data = np.random.randint(low=0, high=5, size=(3, 6))
print(data)
print('   ')
print(np.sum(data, axis=0))

[[1 3 1 4 4 0]
 [1 3 0 4 1 3]
 [3 0 1 2 1 1]]
   
[ 5  6  2 10  6  4]


In [300]:
# Трансляция
vec = np.arange(4)
mtrx = np.ones((3, 4))
print(vec)
print(mtrx)
print('    ')
result = np.empty_like(mtrx)
print(result)
for i_row in range(mtrx.shape[0]):
    result[i_row,:] = mtrx[i_row,:] * vec

print(result)
print(mtrx.shape[0])

[0 1 2 3]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
    
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]
3


In [303]:
# Умножение вектора на матрицу с применением трансляции
vec_m = np.tile(vec, reps=(3, 1))
print(vec_m)
print('   ')
print(vec_m * mtrx)
print('   ')
print(vec * mtrx)
print('   ')
print(2 * mtrx)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
   
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]
   
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]
   
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [305]:
# Умножение с применением трансляции
x = np.ones((4, 1, 1))
y = np.random.randint(0, 5, size=(4, 3, 2))

print((x*y).shape)

(4, 3, 2)


In [309]:
# Изменение размерности
arr = np.arange(20)
print(arr)
mtrx = np.ndarray((4, 5), dtype=np.int32)
mtrx[0, :] = arr[:5]
mtrx[1, :] = arr[5:10]
mtrx[2, :] = arr[10:15]
mtrx[3, :] = arr[15:]

print(mtrx)
print('----')
print(arr.reshape((4, 5)))
print('----')
print(arr.reshape((4, -1)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
----
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
----
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [310]:
# Объединение массивов
x = np.arange(10).reshape((2, 5))
y = np.arange(15).reshape((3, 5))

print(x)
print(y)
print('-------')
print(np.concatenate((x, y), axis=0))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [311]:
# Объединить три массива вдоль колонок
x = np.arange(9).reshape((3, 3))
y = np.arange(12).reshape((3, 4))
z = np.arange(15).reshape((3, 5))

print(x)
print('    ')
print(y)
print('    ')
print(z)
print(' ')
print(np.concatenate((x, y,z), axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
    
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
    
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
 
[[ 0  1  2  0  1  2  3  0  1  2  3  4]
 [ 3  4  5  4  5  6  7  5  6  7  8  9]
 [ 6  7  8  8  9 10 11 10 11 12 13 14]]


In [313]:
# Напишите реализацию добавления стобца единиц к матрице слева:
x = np.arange(1, 10).reshape((3, 3))
print(x)
y = np.ones((3,1))
print('    ')
print(np.concatenate((y,x), axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
    
[[1. 1. 2. 3.]
 [1. 4. 5. 6.]
 [1. 7. 8. 9.]]


In [314]:
# Сортировка массива
unsorted_arr = np.array([2, 4, 5, 1, 2, 7, 5, 0, -1, 3, 5])
sorted_arr = np.sort(unsorted_arr)
print(unsorted_arr)
print(sorted_arr)

[ 2  4  5  1  2  7  5  0 -1  3  5]
[-1  0  1  2  2  3  4  5  5  5  7]


In [316]:
sorted_indices = np.argsort(unsorted_arr)
print(sorted_indices)

# А теперь воспользуемся индексами и отобразим исходный массив с индексацией
print(unsorted_arr[sorted_indices])

# Максимальный элемент
print(np.argmax(unsorted_arr))

# Минимальный элемент
print(np.min(unsorted_arr))

[ 8  7  3  0  4  9  1  2  6 10  5]
[-1  0  1  2  2  3  4  5  5  5  7]
5
-1


In [317]:
# найдите индексы максимальных элементов в каждом столбце 2D матрицы
arr = np.array([
    [11, -1, 1, 3, 5],
    [6, 1, 0, -1, 10],
    [1, 3, 2, 3, 6],
    [5, 2, 7, 8, 9],
])
print(arr)
print(' ')
print(np.argmax(arr, axis=0))

[[11 -1  1  3  5]
 [ 6  1  0 -1 10]
 [ 1  3  2  3  6]
 [ 5  2  7  8  9]]
 
[0 2 3 3 1]


In [318]:
# Напишите код сортировки массива по столбцам:
arr = np.array([
    [11, 2, 1, 3, 5],
    [6, 2, 0, -1, 10],
    [1, 3, 2, 3, 5],
    [5, 2, 7, 8, 9],
])
print(arr)
print(' ')
print(np.sort(arr, axis=0))

[[11  2  1  3  5]
 [ 6  2  0 -1 10]
 [ 1  3  2  3  5]
 [ 5  2  7  8  9]]
 
[[ 1  2  0 -1  5]
 [ 5  2  1  3  5]
 [ 6  2  2  3  9]
 [11  3  7  8 10]]


In [319]:
#Создайте массив, состоящий из случайных элементов в диапазоне [-10; 20] размером (5, 7)
mass=np.random.randint(low=-10, high=20, size=(5,7))
print(mass)

[[-4  4 14 -7  6 -6 15]
 [10 -5 18 13  0 16  9]
 [17 17 -5 17 -9 15 12]
 [-3 -8 18 -6 -4 14 12]
 [16  6 -6 -3 -6 -8  7]]


In [320]:
#Добавьте границу в виде нулей со всех сторон 2D массива:
data = np.arange(1, 16).reshape((3, 5))
print(data)
mass_zero=np.zeros((data.shape[0],1))
cont=np.concatenate((mass_zero,data,mass_zero),axis=1)
new_mass_zero=np.zeros((1,cont.shape[1]))
print(' ')
print(np.concatenate((new_mass_zero,cont,new_mass_zero),axis=0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
 
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  5.  0.]
 [ 0.  6.  7.  8.  9. 10.  0.]
 [ 0. 11. 12. 13. 14. 15.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [321]:
#произведите ограничение массива, чтобы в нем значения были не более шести и не менее двух:
data = np.arange(1, 16).reshape((3, 5))
print(data)
print(' ')
print(np.clip(data,2,6))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
 
[[2 2 3 4 5]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [323]:
#роизведите модификацию массива так, чтобы значение в колонке результата соответствовало исходному значению, возведенному в степень индекса колонки
data = np.full((3, 5), fill_value=2, dtype=np.int32)
print(data)

new_data=np.empty_like(data)
for i in range(data.shape[1]):
    new_data[:,i]=new_data[:,i]**i

print('--------')
print(new_data)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
--------
[[ 1  2  4  8 16]
 [ 1  2  4  8 16]
 [ 1  2  4  8 16]]


In [324]:
#Умножьте каждую колонку на ее индекс:
data = np.full((3, 5), fill_value=2, dtype=np.int32)
print(data)
index=list(range(data.shape[1]))
new_data=np.multiply(data,index)
print(' ')
print(new_data)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
 
[[0 2 4 6 8]
 [0 2 4 6 8]
 [0 2 4 6 8]]


In [325]:
#Умножьте каждый четный ряд в матрице на вектор:
data = np.repeat(np.arange(1, 8), 4).reshape(7, 4)
vec = np.array([1, 2, 1, 2])
new_data=data.copy()
print(data)
for i in range(data.shape[0]):
    if i%2==0:
        new_data[i,:]=np.multiply(new_data[i,:],vec)
print(' ')
print(new_data)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]
 
[[ 1  2  1  2]
 [ 2  2  2  2]
 [ 3  6  3  6]
 [ 4  4  4  4]
 [ 5 10  5 10]
 [ 6  6  6  6]
 [ 7 14  7 14]]


In [326]:
#Определите индексы двух наибольших элементов в матрице по каждому ряду
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
new_data=np.argsort(data, axis=1)
print(' ')
print(new_data)
print(' ')
print(new_data[:,[-1,-2]])

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [ 4 24 24 28  3 40]]
 
[[2 5 3 0 1 4]
 [3 0 5 4 2 1]
 [4 0 2 5 1 3]
 [4 0 1 2 3 5]]
 
[[4 1]
 [1 2]
 [3 1]
 [5 3]]


In [327]:
#Выберите две случайные колонки из массива:

data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
new_data=data[:,[1,-1]]
print(' ')
print(new_data)

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [ 4 24 24 28  3 40]]
 
[[22  8]
 [25 15]
 [16  9]
 [24 40]]


In [328]:
#Создайте массив размером (10, 3), который состоит из повторяющихся рядов исходного массива:

data = np.arange(9).reshape(3, 3)
print(data)
new_data = np.tile(data, reps=(3, 1))
new_data1=np.random.permutation(np.concatenate((new_data[-1:,],new_data), axis=0))
print(' ')
print(new_data1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [6 7 8]
 [3 4 5]
 [6 7 8]
 [3 4 5]
 [6 7 8]]


In [329]:
#Соберите массив, состоящий из элементов 2й и 4й колонок и строк с 1й по 3ю:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 14, 9,  33, 21,  7,  6],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
print('  ')
new_data=data[:,[2,4]]
new_data=new_data[[1,2,3],:]
print(new_data)

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [14  9 33 21  7  6]
 [ 4 24 24 28  3 40]]
  
[[23 22]
 [ 9  0]
 [33  7]]


In [332]:
#Инвертируйте порядок элементов в последних двух колонках:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 14, 9,  33, 21,  7,  6],
                [ 4, 24, 24, 28,  3, 40]])
print(data)
copy_data=data[:,[0,1,2,3]] #копируем часть массива, которая остается без изменений
new_data=data[:,[-2,-1]] #копируем в отдельный массив два последних столбца
stroka=new_data.flatten() # преобразуем два столбца в одну строку
revers_stroka=stroka[(stroka.shape[0])::-1] #переворачиваем строку
mtrx=revers_stroka.reshape(new_data.shape[0],new_data.shape[1]) #восстанавливаем строку в матрицу 5 на 2
mtrx=mtrx[:,[0,1]]=mtrx[:,[1,0]] #меняем столбцы матрицы местами
result=np.concatenate((copy_data,mtrx),axis=1) #присоединяем к неизменной части матрицы два преобразованных последних столбца
print(' ')
print(result)

[[20 22  2 14 25  8]
 [ 7 25 23  3 22 15]
 [ 8 16  9 22  0  9]
 [14  9 33 21  7  6]
 [ 4 24 24 28  3 40]]
 
[[20 22  2 14  3 40]
 [ 7 25 23  3  7  6]
 [ 8 16  9 22  0  9]
 [14  9 33 21 22 15]
 [ 4 24 24 28 25  8]]
